os:
  - linux

dist: xenial

language: python

# Install the codecov pip dependency
install:
  - pip install codecov
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install flask
  - pip install flask_cors
  - pip install coverage
  - pip install pytest-cov
script:
  #- python -m pytest -v
  - coverage run tests/test_dice.py

after_success:
  - bash <(curl -s https://codecov.io/bash)
  #- python 3 -m codecov
