os:
  - linux

dist: xenial

language: python

# Install the codecov pip dependency
install:
  - pip install codecov
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install flask
  - pip install flask_cors
  - pip install coverage

script:
  - python -m pytest -v
  - pwd
  #- coverage run -m unittest discover

after_success:
  #- bash <(curl -s https://codecov.io/bash)
  - python 3 -m codecov
