os:
  - linux

dist: xenial

language: python

# Install the codecov pip dependency
install:
  - pip install codecov
  - python --version
  - pip install -U pip
  - pip install -U pytest

script:
  - python -m pytest -v

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - codecov
