os:
  - linux

dist: xenial

language: python

# Install the codecov pip dependency
install:
  - pip install -r requirements.txt
script:
  #- python -m pytest -v
  - coverage run tests/test_dice.py

after_success:
  - bash <(curl -s https://codecov.io/bash)
  #- python 3 -m codecov
